### ISSUE TITLE
Failed to check integrity of dnscrypt-proxy

### ISSUE THREAD

**Issue by stevenvandervalk** [pwnsdx/RandomDNS#2]
Hey. Love the idea and limited user permissions. 
Unfortunately on updated OS X after 
`npm install -g randomdns && sudo DEBUG=* randomdns` 
running into 
` Failed to check integrity of dnscrypt-proxy` 
am I supposed to supply the 
` --binaryDNSCryptFileSignature [string]`?

Thanks for any help, sorry not sure how to debug.

**Comment by 133txxx** [comment]
how to run this

**Comment by pwnsdx** [comment]
Have you installed dnscrypt-proxy with brew? If no, you can provide the absolute path to the binary with the binaryDNSCryptFile option and its SHA512 signature with the binaryDNSCryptFileSignature option.

You can have the SHA512 signature of a file by typing the following command in the Terminal: `shasum -a 512 [file]`

Also, you can use this method too if you does not have brew (e.g. you are on Linux)

Regards,

**Comment by stevenvandervalk** [comment]
yep it was with brew. hence my confusion.
--
Steve van der Valk
eResearch Centre
James Cook University
M: 0468311883
T: (07) 4781 6904
E: steven.vandervalk@jcu.edu.au<mailto:steven.vandervalk@jcu.edu.au>
L: FSE Building 17, Room 064

On 22 Mar 2016, at 6:17 PM, Sabri Haddouche <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you installed dnscrypt-proxy with brew? If no, you can provide the absolute path to the binary with the binaryDNSCryptFile option and its SHA512 signature with the binaryDNSCryptFileSignature option.

You can have the SHA512 signature of a file by typing the following command in the Terminal: shasum -a 512 [file]

Also, you can use this method too if you does not have brew (e.g. you are on Linux)

Regards,

**Comment by pwnsdx** [comment]
Can you give me the output of this command please? ```stat /usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy```

**Comment by stevenvandervalk** [comment]
Sure, thanks for the help!
`stat /usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy`

`16777220 18410533 -r-xr-xr-x 1 stevenvandervalk admin 0 223728 "Mar 22 23:11:07 2016" "Mar 22 11:31:59 2016" "Mar 22 11:32:01 2016" "Mar 22 11:31:59 2016" 4096 440 0 /usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy
`

**Comment by pwnsdx** [comment]
Strange, could you give me the shasum output on it and give me the version of dnscrypt (by adding the --version option after the binary) please?

**Comment by stevenvandervalk** [comment]
shasum -a 512 /usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy

fc137ca58b8ce2374928d8336a687a708b94436b864217d6637050c434197f5f0d2185936937dbf39a03f44259fca1fec2e1fb7dbf5cdfc51bbd265958870ea5  /usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy

dnscrypt-proxy 1.6.1

**Comment by pwnsdx** [comment]
This is strange, the binary you downloaded is different than the normal one ( https://github.com/pwnsdx/RandomDNS/blob/master/run.js#L59 ). Could you give me the output of brew install dnscrypt-proxy please?

Assuming the binary is legit, you can make it work by adding --binaryDNSCryptFileSignature=fc137ca58b8ce2374928d8336a687a708b94436b864217d6637050c434197f5f0d2185936937dbf39a03f44259fca1fec2e1fb7dbf5cdfc51bbd265958870ea5 after sudo DEBUG=* randomdns

Regards,

**Comment by stevenvandervalk** [comment]
`Warning: dnscrypt-proxy-1.6.1 already installed`

Apologies I just now realised/ suspect I passed `--with-plugins` but that wasn't shown anywhere else so that would explain the hash mismatch. Working now.
