### ISSUE TITLE
-L, --listenOn Seems to fallback to 127.0.0.1

### ISSUE THREAD

**Issue by hitl0r** [pwnsdx/RandomDNS#3]
Even if you define another IP Address (for example 127.0.0.2) with the -L option, the dnscrypt-proxy instance that randomdns starts will still listen on 127.0.0.1

Reproduce:
Start RandomDNS with Option
`-L 127.0.0.2:53`

Effect:
The process randomdns will show the correct commandline option:

`node randomdns -L 127.0.0.2:53`

but the actual dnscrypt will run on 127.0.0.1 anyway:

 `/tmp/dnscrypt-proxy-136461 --local-address 127.0.0.1:53`

**Comment by pwnsdx** [comment]
Fixed in c8f5d59, thanks you!

**Comment by pwnsdx** [comment]
Just released 1.3.1 so you just have to update it :smile:

**Comment by hitl0r** [comment]
Thanks mate!
Cheers
